
services:
  lexer:
    build:
      context: .
      dockerfile: ./lexer/Dockerfile
    container_name: lexer
    ports:
      - "5001:5001"
    networks: [net]

  parser:
    build:
      context: .
      dockerfile: ./parser/Dockerfile
    container_name: parser
    ports:
      - "5002:5002"
    depends_on:
      - lexer
    networks: [net]

  codegen:
    build:
      context: .
      dockerfile: ./codegen/Dockerfile
    container_name: codegen
    ports:
      - "5003:5003"
    volumes:
      - ./output:/output
    depends_on:
      - parser
    networks: [net]

  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    container_name: gateway
    ports:
      - "5000:5000"
    depends_on:
      - lexer
      - parser
      - codegen
    networks: [net]

networks:
  net:
    driver: bridge
